blog/urls.py
from django.urls import path 
from .views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = "blog"

urlpatterns = [
	path('', BlogListView.as_view(), name='home'),
	path('create/',BlogCreateView.as_view(), name='create'),
	path('<int:pk>/', BlogDetailView.as_view(), name= 'detail'),
	path('<int:pk>/update/', BlogUpdateView.as_view(), name= 'update'),
	path('<int:pk>/delete/', BlogDeleteView.as_view(), name= 'delete')
] 

core/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name= 'home'),
    path('blog/', include('blog.urls', namespace='blog')),
]

blog/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
	title = models.CharField(max_length=250)
	content = models.TextField()


	def __str__(self):
		return self.title

blog/forms.py
from django import forms

from .models import Post


class PostCreateForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = ('title', 'content')

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import View, UpdateView, DeleteView
from .forms import PostCreateForm
from .models import Post
from django.urls import reverse_lazy
# Create your views here.

class BlogListView(View):
	def get(self, request, *args, **kwargs):
		posts = Post.objects.all()
		context = {
			'posts': posts
		}
		return render(request, 'blog_list.html', context)

class BlogCreateView(View):
	def get(self, request, *args, **kwargs):
		form = PostCreateForm()
		context = {
			'form': form
		}
		return render(request, 'blog_create.html', context)
	def post(self, request, *args, **kwargs):
		if request.method == 'POST':
			form = PostCreateForm(request.POST)
			if form.is_valid():
				title = form.cleaned_data.get('title')
				content = form.cleaned_data.get('content')

				p, created = Post.objects.get_or_create(title=title, content=content)
				p.save()
				return redirect('blog:home') 
		context = {

		}
		return render(request, 'blog_create.html', context)	

class BlogDetailView(View):
	def get(self, request, pk,*args, **kwargs):
		post = get_object_or_404(Post, pk=pk)
		context = {
			'post':post
		}
		return render(request, 'blog_detail.html', context)

class BlogUpdateView(UpdateView):
	model = Post
	fields = ['title', 'content']
	template_name = 'blog_update.html'

	def get_success_url(self):
		pk = self.kwargs['pk']
		return reverse_lazy('blog:detail', kwargs= {'pk': pk})

class BlogDeleteView(DeleteView):
	model = Post
	template_name = 'blog_delete.html'
	success_url = reverse_lazy('blog:home')

core/views.py
from django.views.generic import View
from django.shortcuts import render


class HomeView(View):
	def get(self, request, *args, **kwargs):
		context = {

		}
		return render(request, 'index.html', context)

templates/base.html
{% load tailwind_tags %}
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE-edge">
	<meta name="viewport" content="width-divice-width, initial-scale=1.0">
	{% tailwind_css %}
</head>
<body>
	{% block content %} {% endblock %}
</body>
</html>

templates/blog_create.html
{% extends 'base.html' %}

{% block content%}
<form class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4" method="POST">
	{% csrf_token %}
	<h1 ass="block w-full text-grey-darkest mb-8">title</h1>{{form.title}}
	<br>
	<h2 ass="block w-full text-grey-darkest mb-8">content</h2>{{form.content}}
	<br>
	<button class="bg-green-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" type="submit">Submit</button>
</form>

{% endblock %}

templates/blog_delete.html
{% extends 'base.html' %}

{% block content%}
<form class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4" method="POST">
	{% csrf_token %}
	<h2 class="block w-full text-grey-darkest mb-8">Delete</h2>
	{{form}}
	<button class="bg-red-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" type="submit">Delete</button>
</form>
{% endblock %}

templates/blog_detail.html
{% extends 'base.html' %}

{% block content%}

	<h1 class="block w-full text-grey-darkest mb-8">{{post.title}}</h1>
	<br>
	<h2 class="block w-full text-grey-darkest mb-8">{{post.content}}</h2>
	

{% endblock %}

templates/blog_list.html
{% extends 'base.html' %}

{% block content%}
<h1 class="block w-full text-grey-darkest mb-8">Blog list</h1>
<br>
{%for post in posts%}
	<a class="bg-green-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" href="{% url 'blog:detail' post.id %}">{{post.title}}</a>
	<a class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" href="{% url 'blog:update' post.id %}">Update</a>
	<a class="bg-red-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" href="{% url 'blog:delete' post.id %}">Delete</a>
	<br>
	<br>
{% endfor%}
<br>
<a class="bg-green-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" href="{% url 'blog:create' %}">Create</a>
{% endblock %}

templates/blog_update.html
{% extends 'base.html' %}

{% block content%}
<form class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4" method="POST">
	{% csrf_token %}
	<h1 class="block w-full text-grey-darkest mb-8">title</h1>{{form.title}}
	<br>
	<h2 class="block w-full text-grey-darkest mb-8">content</h2>{{form.content}}
	<br>
	<button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"type="submit">Update</button>
</form>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block content %}
hola vivista mi <a class="text-blue-500" href="{% url 'blog:home' %}">blog aqui</a>
{% endblock %}

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-grey-lightest font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>